# Generated by Django 5.2.13 on 2026-08-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CPU', 'CPU'), ('MEMORY', 'Memory'), ('DISK', 'Disk'), ('NETWORK', 'Network'), ('PROCESSES', 'Processes'), ('SERVICES', 'Services'), ('OS', 'OS'), ('TCP_FIN_WAIT', 'TCP FIN WAIT')], max_length=50)),
                ('linux_command', models.TextField(blank=True, null=True)),
                ('windows_command', models.TextField(blank=True, null=True)),
                ('execution_order', models.PositiveIntegerField(default=1)),
                ('interval_seconds', models.PositiveIntegerField(default=60)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('operating_system', models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows')], default='LINUX', max_length=20)),
                ('ssh_username', models.CharField(blank=True, max_length=100, null=True)),
                ('pem_file', models.FileField(blank=True, null=True, upload_to='pem/')),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('application_name', models.CharField(blank=True, max_length=150, null=True)),
                ('environment', models.CharField(default='PROD', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.kpi')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='infrastructure.server')),
            ],
        ),
    ]
