# Generated by Django 5.2.13 on 2026-08-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_remove_kpi_description_remove_kpi_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='interval_seconds',
        ),
    ]
