# Generated by Django 5.2.13 on 2026-08-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_remove_kpi_interval_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='updated_at',
        ),
    ]
