# Generated by Django 5.2.13 on 2026-08-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_remove_kpi_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metricsample',
            old_name='collected_at',
            new_name='collection_time',
        ),
        migrations.RenameField(
            model_name='metricsample',
            old_name='metric_name',
            new_name='metric_type',
        ),
        migrations.RenameField(
            model_name='metricsample',
            old_name='value',
            new_name='metric_value',
        ),
        migrations.RemoveField(
            model_name='metricsample',
            name='kpi',
        ),
        migrations.RemoveField(
            model_name='metricsample',
            name='text_value',
        ),
        migrations.AlterField(
            model_name='kpi',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
