# Generated by Django 5.2.13 on 2026-08-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_networkmetric_processmetric_servicemetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkmetric',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='networkmetric',
            name='state',
        ),
        migrations.RemoveField(
            model_name='processmetric',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='servicemetric',
            name='collection_status',
        ),
    ]
