# Generated by Django 5.2.13 on 2026-08-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_remove_networkmetric_collection_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KPI',
        ),
    ]
