# Generated by Django 5.2.13 on 2026-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_delete_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmetric',
            name='server',
        ),
        migrations.RemoveField(
            model_name='servicemetric',
            name='server',
        ),
        migrations.AlterField(
            model_name='metricsample',
            name='metric_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='NetworkMetric',
        ),
        migrations.DeleteModel(
            name='ProcessMetric',
        ),
        migrations.DeleteModel(
            name='ServiceMetric',
        ),
    ]
