# Generated by Django 5.2.13 on 2026-08-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_remove_processmetric_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=10)),
                ('local_address', models.CharField(blank=True, max_length=100, null=True)),
                ('local_port', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_address', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_port', models.PositiveIntegerField(blank=True, null=True)),
                ('collection_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_metrics', to='infrastructure.server')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('handle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('collection_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_metrics', to='infrastructure.server')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('start_type', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_metrics', to='infrastructure.server')),
            ],
        ),
    ]
