# Generated by Django 5.2.13 on 2026-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_networkmetric_processmetric_servicemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmetric',
            name='cpu_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='CPU %'),
        ),
        migrations.AddField(
            model_name='processmetric',
            name='memory_mb',
            field=models.FloatField(blank=True, null=True, verbose_name='Memory (MB)'),
        ),
    ]
