# Generated by Django 5.2.13 on 2026-08-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_processmetric_cpu_percent_processmetric_memory_mb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemetric',
            old_name='start_type',
            new_name='startup_type',
        ),
    ]
